### ISSUE TITLE
1.76 now requires unicode paths on windows

### ISSUE THREAD

**Issue by rconde01** [boostorg/interprocess#145]
If you use BOOST_INTERPROCESS_SHARED_DIR_PATH with std::string, you now get a compile error on windows because BOOST_INTERPROCESS_WCHAR_NAMED_RESOURCES is unconditionally true.

**Comment by rconde01** [comment]
just realized its broken because no matter what you pick, there's a wchar_t and char overload of shared_memory_object::remove

**Comment by igaztanaga** [comment]
I didn't notice the breakage, because there was no associated test in the testsuite. I've modified the documentation to notice that BOOST_INTERPROCESS_SHARED_DIR_WPATH should be added in  Windows and modified the implementation to be able to compile without BOOST_INTERPROCESS_SHARED_DIR_WPATH (it will use standard shared memory path for wide functions). 

Also added a test for the feature so that some bugs can be detected in the future when changing internals.
