### ISSUE TITLE
Commit 140b50e: windows_shared_memory::priv_open_or_create doesn't anymore set member m_name

### ISSUE THREAD

**Issue by aholzinger** [boostorg/interprocess#153]
After constructing a windows_shared_memory member m_name remains empty, while it should reflect the name given to the windows_shared_memory object in the c'tor.

The issue was introduced with commit 140b50e. The line
`m_name = filename ? filename : "";`
was removed, but no other code to set m_name was added.

**Comment by yobeonline** [comment]
I ran into this problem too.

**Comment by yobeonline** [comment]
The new implementation is actually broken because `get_name` returns `m_name.getn()` regardless of the width of the string actually stored in `m_name`. As a result, If `m_name` was initialized with a `const wchar_t *` then `get_name()` would still return 0, even if `if (filename) m_name = filename;` was reintroduced in the code.

**Comment by igaztanaga** [comment]
This was fixed in #171.

**Comment by aholzinger** [comment]
Good news, thank you!
